export const siteConfig = {
  name: 'Høyde Sikkerhet AS',
  description: 'Norges ledende eksperter på fallsikring, arbeid i høyden, rope access og redningstjenester. Sertifiserte løsninger for trygg arbeid i høyden.',
  url: 'https://hoydesikkerhet.no',
  ogImage: 'https://hoydesikkerhet.no/og-image.jpg',
  contact: {
    phone: '+47 22 33 44 55',
    email: 'post@hoydesikkerhet.no',
    address: 'Industriveien 42, 0579 Oslo',
  },
  social: {
    linkedin: 'https://linkedin.com/company/hoydesikkerhet',
    facebook: 'https://facebook.com/hoydesikkerhet',
    instagram: 'https://instagram.com/hoydesikkerhet',
  },
  navigation: {
    main: [
      { 
        title: 'Tjenester', 
        href: '/tjenester',
        children: [
          { title: 'Fallsikring', href: '/tjenester/fallsikring' },
          { title: 'Arbeid i høyden', href: '/tjenester/arbeid-i-hoyden' },
          { title: 'Rope Access', href: '/tjenester/rope-access' },
          { title: 'Redningstjenester', href: '/tjenester/redningstjenester' },
          { title: 'Kurs og opplæring', href: '/tjenester/kurs' },
          { title: 'Inspeksjon', href: '/tjenester/inspeksjon' },
          { title: 'Vedlikehold', href: '/tjenester/vedlikehold' },
          { title: 'Risikoanalyse', href: '/tjenester/risikoanalyse' },
        ]
      },
      { title: 'Om oss', href: '/om-oss' },
      { title: 'Blogg', href: '/blogg' },
      { title: 'FAQ', href: '/faq' },
      { title: 'Kontakt', href: '/kontakt' },
    ],
    footer: {
      services: [
        { title: 'Fallsikring', href: '/tjenester/fallsikring' },
        { title: 'Rope Access', href: '/tjenester/rope-access' },
        { title: 'Redningstjenester', href: '/tjenester/redningstjenester' },
        { title: 'Kurs og opplæring', href: '/tjenester/kurs' },
        { title: 'Inspeksjon', href: '/tjenester/inspeksjon' },
      ],
      company: [
        { title: 'Om oss', href: '/om-oss' },
        { title: 'Vårt team', href: '/om-oss#team' },
        { title: 'Karriere', href: '/karriere' },
        { title: 'Sertifiseringer', href: '/om-oss#sertifiseringer' },
      ],
      resources: [
        { title: 'Blogg', href: '/blogg' },
        { title: 'FAQ', href: '/faq' },
        { title: 'Nedlastinger', href: '/ressurser' },
        { title: 'Regelverk', href: '/blogg?kategori=regelverk' },
      ],
      legal: [
        { title: 'Personvern', href: '/personvern' },
        { title: 'Vilkår', href: '/vilkar' },
        { title: 'Cookies', href: '/cookies' },
      ],
    },
  },
  certifications: [
    { name: 'ISO 9001:2015', description: 'Kvalitetsledelse' },
    { name: 'ISO 45001:2018', description: 'HMS-ledelse' },
    { name: 'IRATA', description: 'Industrial Rope Access' },
    { name: 'SOFT', description: 'Skandinavisk organisasjon for fallsikring' },
  ],
  stats: [
    { value: '15+', label: 'Års erfaring' },
    { value: '500+', label: 'Prosjekter fullført' },
    { value: '2000+', label: 'Kurs deltakere' },
    { value: '100%', label: 'Skadefrie oppdrag' },
  ],
}

export const services = [
  {
    slug: 'fallsikring',
    title: 'Fallsikring',
    shortDescription: 'Komplette fallsikringssystemer og utstyr for trygg arbeid i høyden.',
    description: 'Vi leverer skreddersydde fallsikringsløsninger tilpasset dine behov. Fra risikovurdering til installasjon og opplæring.',
    icon: 'Shield',
    features: [
      'Permanente fallsikringssystemer',
      'Midlertidige løsninger',
      'Forankringspunkter',
      'Livliner og horisontale systemer',
      'Personlig verneutstyr',
    ],
  },
  {
    slug: 'arbeid-i-hoyden',
    title: 'Arbeid i høyden',
    shortDescription: 'Profesjonelle tjenester for alle typer arbeid i høyden.',
    description: 'Våre sertifiserte teknikere utfører arbeid i høyden på en sikker og effektiv måte, uansett kompleksitet.',
    icon: 'Mountain',
    features: [
      'Takarbeid og vedlikehold',
      'Fasadearbeid',
      'Vindkraftinstallasjoner',
      'Solcellemontasje',
      'Industrielt vedlikehold',
    ],
  },
  {
    slug: 'rope-access',
    title: 'Rope Access',
    shortDescription: 'IRATA-sertifisert rope access for vanskelig tilgjengelige områder.',
    description: 'Med industriell tau-tilgang når vi steder der tradisjonelt utstyr ikke fungerer. Sikkert, effektivt og kostnadsbesparende.',
    icon: 'Cable',
    features: [
      'Inspeksjon og NDT',
      'Vedlikehold og reparasjon',
      'Maling og overflatebehandling',
      'Installasjon',
      'Offshore operasjoner',
    ],
  },
  {
    slug: 'redningstjenester',
    title: 'Redningstjenester',
    shortDescription: 'Beredskap og redning ved arbeid i høyden.',
    description: 'Vi tilbyr redningstjenester og beredskap for å sikre rask og trygg evakuering ved nødssituasjoner.',
    icon: 'Ambulance',
    features: [
      'Redningsplaner',
      'Beredskapsmannskap',
      'Evakueringsøvelser',
      'Redningsteknikker',
      '24/7 beredskap',
    ],
  },
  {
    slug: 'kurs',
    title: 'Kurs og opplæring',
    shortDescription: 'Sertifiserte kurs innen fallsikring og arbeid i høyden.',
    description: 'Vi tilbyr omfattende opplæring for alle nivåer, fra grunnleggende sikkerhetskurs til avansert rope access.',
    icon: 'GraduationCap',
    features: [
      'Grunnkurs fallsikring',
      'IRATA Level 1-3',
      'Redningskurs',
      'Årlig oppfriskningskurs',
      'Bedriftsinterne kurs',
    ],
  },
  {
    slug: 'inspeksjon',
    title: 'Inspeksjon',
    shortDescription: 'Grundig kontroll og sertifisering av fallsikringsutstyr.',
    description: 'Regelmessig inspeksjon av fallsikringsutstyr er lovpålagt. Vi utfører årskontroll iht. NS-EN 365.',
    icon: 'Search',
    features: [
      'Årskontroll utstyr',
      'Systemkontroll',
      'Dokumentasjon',
      'Kassering og utskifting',
      'Kontrollrapporter',
    ],
  },
  {
    slug: 'vedlikehold',
    title: 'Vedlikehold',
    shortDescription: 'Service og vedlikehold av fallsikringssystemer.',
    description: 'Regelmessig vedlikehold sikrer at systemene fungerer optimalt og ivaretar sikkerheten.',
    icon: 'Wrench',
    features: [
      'Forebyggende vedlikehold',
      'Reparasjoner',
      'Utskifting av komponenter',
      'Systemoppgraderinger',
      'Serviceavtaler',
    ],
  },
  {
    slug: 'risikoanalyse',
    title: 'Risikoanalyse',
    shortDescription: 'HMS-rådgivning og risikovurdering for arbeid i høyden.',
    description: 'Vi hjelper deg med å identifisere farer og implementere tiltak for sikker arbeid i høyden.',
    icon: 'ClipboardCheck',
    features: [
      'SJA - Sikker Jobb Analyse',
      'Risikovurdering',
      'HMS-dokumentasjon',
      'Beredskapsplaner',
      'Prosedyreutvikling',
    ],
  },
]

export const testimonials = [
  {
    quote: 'Høyde Sikkerhet har vært vår partner i over 5 år. Deres profesjonalitet og kompetanse er uovertruffen.',
    author: 'Lars Henriksen',
    role: 'HMS-sjef',
    company: 'Statoil Offshore',
  },
  {
    quote: 'Kursene deres ga oss den kunnskapen vi trengte for å jobbe trygt i høyden. Sterkt anbefalt!',
    author: 'Maria Olsen',
    role: 'Prosjektleder',
    company: 'Veidekke ASA',
  },
  {
    quote: 'Rask respons, høy kvalitet og alltid fokus på sikkerhet. En pålitelig samarbeidspartner.',
    author: 'Erik Johansen',
    role: 'Driftssjef',
    company: 'Statkraft',
  },
]
