export const siteConfig = {
  name: "ABC Sikkerhet AS",
  shortName: "ABC Sikkerhet",
  description:
    "ABC Sikkerhet AS er eksperter på fallsikring, arbeid i høyden, rope access og redningstjenester. Autorisert forhandler av Skylotec, Petzl og Actsafe taumopeder (ACX, ICX, PMX, PME, ACC). Sertifiserte kurs og godkjente redningssett til byggeplass.",
  url: "https://abcfallsikring.no",
  ogImage: "https://abcfallsikring.no/og-image.jpg",
  email: "finn@abcfallsikring.no",
  phone: "+47 33 74 08 88",
  address: {
    street: "Korniveien 1",
    city: "Barkåker",
    zip: "3157",
    country: "Norge",
  },
  organizationNumber: "922 646 260",
  social: {
    facebook: "https://www.facebook.com/abcfallsikring",
    linkedin: "https://www.linkedin.com/company/abc-fallsikring",
    instagram: "https://www.instagram.com/abcfallsikring",
  },
  keywords: [
    "fallsikring",
    "arbeid i høyden",
    "rope access",
    "industriell klatring",
    "redningstjenester",
    "redningssett",
    "umiddelbar redning",
    "HMS",
    "fallsikringsutstyr",
    "kurs fallsikring",
    "Norge",
    "Skylotec",
    "Petzl",
    "Actsafe",
    "taumoped",
    "ACX",
    "ICX",
    "PMX",
    "PME",
    "ACC",
    "IRATA",
    "SOFT",
    "hengetrauma",
    "fallsele",
    "ABC fallsikring",
    "ABC Sikkerhet",
  ],
  openingHours: "Man–Fre 07:00–16:00",
  certifications: ["ISO 9001:2015", "ISO 45001:2018", "IRATA", "SOFT"],
}

export type SiteConfig = typeof siteConfig
